### ISSUE TITLE
Tameble Spiders: Visible placeholder text

### ISSUE THREAD

**Issue by kyropy** [Spiderman31807/Tameable#8]
Version: 1.21.1 NeoForge

I'm not too sure if these were supposed to be visible, but some text associated with the mod use the "placeholder" text and also another bug is that hovering over the saddle box in the spider's inventory.. reveals a tooltip?

Screenshots: 
![Screenshot_20240913_001212](https://github.com/user-attachments/assets/0645520c-c106-43ef-9f19-4afff86c7b71)
![Screenshot_20240913_001140](https://github.com/user-attachments/assets/6f5d9f92-e05c-44c6-80f7-831dcf757ca9)
![Screenshot_20240913_001045](https://github.com/user-attachments/assets/ca213942-af60-40d6-bf56-57e4f02a909f)
![Screenshot_20240913_001018](https://github.com/user-attachments/assets/a1c43679-b03b-4014-aa69-cfb86414b7db)

**Comment by Spiderman31807** [comment]
Those aren't Placeholders, those are the path to the translocation for the string. some of these are done by Mcreator so its automatically generating it, others are made in custom code blocks by me, so i have to add them manually.

if the translation is not found it'll default to displaying the path itself. the Tooltip for the saddle, is intended and added manually by me as well as all the others you've shown.. the Tooltip just tells the Player that they can Mount the Spider by pressing Control.

looking at the files now, it appears (not the first time tbh) I've gotten too eager in thinking the mod was done being ported and just uploaded it, however i forgot to add all the custom translations for what I manually added (as well as the 26 or something other languages.. that's also manual, takes like half an hour or something)

**Comment by Spiderman31807** [comment]
All 45 Translation Keys have been added to 1.21.1 NeoForge, as well as the 26 Languages. and a few Types in the Translations themselves were also fixed.

`respawning` was spelt `repsawning` in one of the translations
`different` was spelt `diffrent` in one of the translations
`venom` was spelt `vemon` in two of the translations.
